/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inventory;

public class App {

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}

	public String getGreeting() {
		return "Welcome to Tracking Inventory";
	}

}
